### ISSUE TITLE
Fatal error in oro:message:consume

### ISSUE THREAD

**Issue by gplanchat** [orocommerce/orocommerce#27]
While running command `app/console oro:message:consume --env prod --process-isolation -vvv
` a fatal error happened :

```
[debug] Payload: '{"jobId":1154}'
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "default"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "config"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "message_queue_job"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "search"
[info] Message processed: oro.message_queue.consumption.ack
[debug] Switch to a queue oro.default
[info] Pre receive Message
[info] Message received
[debug] Headers: array (
  'content_type' => 'application/json',
  'message_id' => 'oro.58dd0d25b2c702.50659987',
  'timestamp' => 1490881829,
)
[debug] Properties: array (
  'oro.message_queue.client.topic_name' => 'oro.message_queue.job.calculate_root_job_status',
  'oro.message_queue.client.processor_name' => 'oro_message_queue.job.calculate_root_job_status_processor',
  'oro.message_queue.client.queue_name' => 'oro.default',
)
[debug] Payload: '{"jobId":1154}'
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "default"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "config"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "message_queue_job"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "search"
[info] Message processed: oro.message_queue.consumption.ack
[debug] Switch to a queue oro.default
[info] Pre receive Message
[info] Message received
[debug] Headers: array (
  'content_type' => 'application/json',
  'message_id' => 'oro.58dd0d257cc998.42710349',
  'timestamp' => 1490881829,
)
[debug] Properties: array (
  'oro.message_queue.client.topic_name' => 'oro.integration.sync_integration',
  'oro.message_queue.client.processor_name' => 'oro_integration.async.sync_integration_processor',
  'oro.message_queue.client.queue_name' => 'oro.default',
)
[debug] Payload: '{"integration_id":1,"connector_parameters":[],"connector":null,"transport_batch_size":100}'
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "default"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "config"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "message_queue_job"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "search"
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken::setOrganizationContext() in /home/webuser/htdocs/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/Async/SyncIntegrationProcessor.php:161
Stack trace:
#0 /home/webuser/htdocs/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/Async/SyncIntegrationProcessor.php(133): Oro\Bundle\IntegrationBundle\Async\SyncIntegrationProcessor->updateToken(Object(Oro\Bundle\IntegrationBundle\Entity\Channel))
#1 /home/webuser/htdocs/vendor/oro/platform/src/Oro/Component/MessageQueue/Client/DelegateMessageProcessor.php(36): Oro\Bundle\IntegrationBundle\Async\SyncIntegrationProcessor->process(Object(Oro\Component\MessageQueue\Transport\Dbal\DbalMessage), Object(Oro\Component\MessageQueue\Transport\Dbal\DbalSession))
#2 /home/webuser/htdocs/vendor/oro/platform/src/Oro/Component/MessageQueue/Consumption/QueueConsumer.php(183): Oro\Component\MessageQueue\Client\DelegateMessageProcessor->process(Object(Oro\Componen in /home/webuser/htdocs/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/Async/SyncIntegrationProcessor.php on line 161
```

The command then runs again normally.

**Comment by manowark** [comment]
Hi, @gplanchat and thank you for your request!
It is known bug and it will be fixed in next release.

**Comment by manowark** [comment]
Hi, @gplanchat. I hope you got new update. Issue still present?

**Comment by sprightly** [comment]
Issue closed as it has been inactive for a while. Please, feel free to reopen it if you have any questions.

**Comment by manowark** [comment]
Issue closed as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
